### PR TITLE
Base development

### PR DESCRIPTION
**Pull request by haroldangenent**
Work in progress.

### CODE REVIEW

**Comment by luukdv** [comment]
https://github.com/trendwerk/search/blob/base/README.md#install doesn't point to the current package yet.

**Comment by luukdv** [comment]
https://github.com/trendwerk/search/blob/base/README.md#example: I would drop the namespace in both initializations for consistency (so `new Search` and `new Meta` instead of `new \Trendwerk\Search\Search` and `new Meta`).

**Review by luukdv — APPROVED** [review]
Great work. Can you look at the Readme details above before merging?

**Comment by haroldangenent** [comment]
Guess I got tired near the end. Thanks @luukdv!

**Pull request merged**
